# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=19)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
            options={
                'ordering': ('created', 'longitude', 'latitude'),
            },
        ),
    ]
